# Generated by Django 4.2.5 on 2023-10-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_name", models.CharField(max_length=100, null=True)),
                ("headquarter", models.CharField(max_length=100, null=True)),
                ("website", models.URLField(null=True)),
                ("president", models.CharField(max_length=150, null=True)),
                ("coach", models.CharField(max_length=150, null=True)),
                ("assistant_coach", models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100, null=True)),
                ("surname", models.CharField(max_length=100, null=True)),
                ("role", models.CharField(max_length=50, null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("nationality", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeasonPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("season_part", models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stadium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stadium_name", models.CharField(max_length=100, null=True)),
                ("capacity", models.PositiveIntegerField(null=True)),
                ("guest_sector_capacity", models.PositiveIntegerField(null=True)),
                ("year_of_construction", models.PositiveIntegerField(null=True)),
                ("city", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
