# Generated by Django 4.2.5 on 2023-10-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballstats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="guest_score",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_score",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="matchday",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="matchaction",
            name="minute",
            field=models.IntegerField(null=True),
        ),
    ]
