# Generated by Django 4.2.5 on 2023-10-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "footballstats",
            "0002_match_guest_score_match_home_score_match_matchday_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("season_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerClubOfSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="footballstats.club",
                    ),
                ),
                (
                    "player_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="footballstats.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="footballstats.season",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="match",
            name="season_part",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="footballstats.season",
            ),
        ),
        migrations.DeleteModel(
            name="SeasonPart",
        ),
    ]
