# Generated by Django 4.2.5 on 2023-10-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "footballstats",
            "0003_season_playerclubofseason_alter_match_season_part_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="stadium",
            new_name="stadium_id",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="guest_team",
            new_name="guest_team_id",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="home_team",
            new_name="home_team_id",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="season_part",
            new_name="season_id",
        ),
        migrations.RenameField(
            model_name="matchaction",
            old_name="match_player",
            new_name="match_player_id",
        ),
        migrations.RenameField(
            model_name="matchplayer",
            old_name="match",
            new_name="match_id",
        ),
        migrations.RenameField(
            model_name="matchplayer",
            old_name="player",
            new_name="player_id",
        ),
        migrations.RenameField(
            model_name="playerclubofseason",
            old_name="season",
            new_name="season_id",
        ),
    ]
