# Generated by Django 4.2.5 on 2023-10-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footballstats", "0004_rename_stadium_club_stadium_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="stadium_id",
            new_name="stadium",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="guest_team_id",
            new_name="guest_team",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="home_team_id",
            new_name="home_team",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="season_id",
            new_name="season",
        ),
        migrations.RenameField(
            model_name="playerclubofseason",
            old_name="club_id",
            new_name="club",
        ),
        migrations.RenameField(
            model_name="playerclubofseason",
            old_name="player_id",
            new_name="player",
        ),
        migrations.RenameField(
            model_name="playerclubofseason",
            old_name="season_id",
            new_name="season",
        ),
    ]
