# Generated by Django 4.2.5 on 2023-10-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("footballstats", "0007_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerclubofseason",
            name="club",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seasonteam_set",
                to="footballstats.club",
            ),
        ),
        migrations.AlterField(
            model_name="playerclubofseason",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seasonteam_set",
                to="footballstats.player",
            ),
        ),
        migrations.AlterField(
            model_name="playerclubofseason",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seasonteam_set",
                to="footballstats.season",
            ),
        ),
    ]
